name = "pleasehire"
type = "javascript"
account_id = "3a4d09d4849f8588ce3da46dde627ad5"
workers_dev = true

[env.production]
# The ID of your domain you're deploying to
zone_id = "0123e91c473f9eceac149fcfe3a10d92"
account_id = "3a4d09d4849f8588ce3da46dde627ad5"
# The route pattern your Workers application will be served at
route = "*pleasehire.ianmah.com/*"